
@mech-id=1

### GET Mechs
GET http://localhost:8081/mechs

### GET Available Parts
GET http://localhost:8081/mechs/availableParts

### Start new Mech
POST http://localhost:8081/mechs

### Add part1 to mech
POST http://localhost:8081/mechs/{{mech-id}}/parts
Content-Type: application/json

{
  "id": 1
}

### Add part1 to mech
POST http://localhost:8081/mechs/{{mech-id}}/parts
Content-Type: application/json

{
  "id": 3
}

### Add part1 to mech
POST http://localhost:8081/mechs/{{mech-id}}/parts
Content-Type: application/json

{
  "id": 5
}
