version: "3.9"
services:
  lb:
    image: haproxy:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:80"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./development/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro