drop table if exists invalid_players;
drop table if exists players;
drop table if exists import_players_atp;
drop table if exists import_players_wta;

create table players (
                         player_id bigint primary key,
                         tour varchar(3),
                         name_first varchar(50),
                         name_last varchar(100),
                         hand char(1),
                         dob char(12),
                         ioc varchar(10),
                         height int,
                         wikidata_id varchar(20)
);


create table import_players_wta (
                                    player_id bigint,
                                    name_first varchar(50),
                                    name_last varchar(100),
                                    hand char(1),
                                    dob char(12),
                                    ioc varchar(10),
                                    height int,
                                    wikidata_id varchar(20)
);

create table import_players_atp (
                                    player_id bigint,
                                    name_first varchar(50),
                                    name_last varchar(100),
                                    hand char(1),
                                    dob char(12),
                                    ioc varchar(10),
                                    height int,
                                    wikidata_id varchar(20)
);

create table invalid_players (
                                 player_id bigint,
                                 name_first varchar(50),
                                 name_last varchar(100),
                                 hand char(1),
                                 dob char(12),
                                 ioc varchar(10),
                                 height int,
                                 wikidata_id varchar(20),
                                 reason varchar(100)
);

COPY import_players_atp
    FROM '/raw/tennis_atp/atp_players.csv'
    DELIMITER ','
    CSV HEADER;

with invalids as
         (select player_id, count(*) from import_players_atp p
          group by player_id
          having count(*) > 1)
insert into invalid_players
select p.*, 'duplicate_id' from import_players_atp p
                                    join invalids i on p.player_id = i.player_id;

delete from import_players_atp p
    using invalid_players ip
where ip.player_id = p.player_id;

insert into players(player_id, tour, name_first, name_last, hand, dob, ioc, height, wikidata_id)
select player_id, 'atp', name_first, name_last, hand, dob, ioc, height, wikidata_id
from import_players_atp;

COPY import_players_wta
    FROM '/raw/tennis_wta/wta_players.csv'
    DELIMITER ','
    CSV HEADER;

with invalids as
         (select player_id, count(*) from import_players_wta p
          group by player_id
          having count(*) > 1)
insert into invalid_players
select p.*, 'wta_duplicate_id' from import_players_wta p
                                        join invalids i on p.player_id = i.player_id;

delete from import_players_wta p
    using invalid_players ip
where ip.player_id = p.player_id;

insert into players(player_id, tour, name_first, name_last, hand, dob, ioc, height, wikidata_id)
select (player_id + 300000), 'wta', name_first, name_last, hand, dob, ioc, height, wikidata_id
from import_players_wta;

--alter table players alter column player_id drop identity ;
ALTER TABLE players
    ALTER COLUMN player_id
        ADD GENERATED BY DEFAULT AS IDENTITY (MINVALUE 1 START WITH 1000000 INCREMENT BY 1);
